"""
Geo AI 干旱区遥感智能分析平台 — 工具模块
"""

from .indices import calc_ndvi, calc_mndwi, calc_evi, calc_aweish, load_bands_from_geotiff
from .visualization import (
    render_classification, render_ndvi, render_mndwi,
    render_multilevel_change, render_change_overlay,
    plot_multilevel_change_stacked_bar, plot_trend_scatter,
)
from .landcover import (
    ESA_CLASSES, ARID6_CLASSES, ESRI_CLASSES,
    ESA_TO_ARID6, ESRI_TO_ARID6,
    esa_to_arid6, esri_to_arid6,
    get_landcover_for_study_area, compute_landcover_stats,
    get_tile_list_for_area, export_landcover_geotiff,
)
from .ai_engine import (
    segment_water_ai, segment_water_ai_batch,
    build_band_order, get_model_info,
    SENTINEL2_BAND_ORDER, DEFAULT_SEGMENT_PARAMS,
)
from .trend import (
    calc_sen_mk_trend, calc_sen_mk_trend_pixelwise,
    calc_mean_timeseries_trend, theil_sen_slope,
    savgol_smooth, smooth_ndvi_stack,
    stl_decompose,
)
from .forecast import (
    ForecastResult,
    prepare_ndvi_timeseries, split_train_test, evaluate_forecast,
    forecast_sarima, forecast_lstm, forecast_holt_winters,
    forecast_drought_trend,
    plot_forecast, plot_forecast_comparison,
    analyze_drought_forecast,
)
from .export import (
    export_raster_geotiff, export_index_geotiff, export_mask_geotiff,
    export_classification_geotiff,
    export_csv, export_stats_csv, export_timeseries_csv,
    export_figure, export_array_as_image, export_comparison_figure,
    export_timeseries_plot,
    raster_to_geojson_polygons, export_change_polygons_geojson,
    export_numpy, export_batch, make_download_label,
)
from .onnx_engine import (
    check_onnx_available, get_ort_session,
    export_to_onnx, run_onnx_inference,
    segment_water_onnx, benchmark_onnx_vs_pytorch,
    inspect_onnx_model,
    DEFAULT_WINDOW_SIZE, DEFAULT_OVERLAP,
)
from .error_handler import (
    with_retry, safe_execute,
    StreamlitErrorBoundary, streamlit_safe,
    StreamlitProgress, check_dependencies,
    get_memory_usage_mb, safe_cleanup,
)
from .drought import (
    DROUGHT_CATEGORIES, SPI_THRESHOLDS, VCI_THRESHOLDS,
    classify_drought, classify_spi, classify_vci,
    calc_spi, calc_spi_pixelwise,
    calc_pet_thornthwaite, calc_spei,
    calc_vci, calc_vci_pixelwise,
    calc_tci, calc_tci_pixelwise,
    calc_vhi, calc_vhi_pixelwise,
    calc_nddi, calc_ndwi_s2,
    calc_ndvi_anomaly, calc_ndvi_anomaly_pixelwise,
    calc_tvdi,
    calc_composite_drought_index,
    compute_drought_stats, compute_drought_index_stats,
    analyze_drought_remote,
)
from .desertification import (
    DESERTIFICATION_LEVELS, DesertificationResult,
    calc_albedo_s2, calc_albedo_landsat,
    calc_tgsi, calc_ndmi, calc_ddi,
    classify_desertification, compute_desertification_stats,
    assess_desertification, assess_desertification_cached,
    analyze_desertification_trend, get_desertification_colormap,
)
from .salinity import (
    SALINITY_LEVELS, SalinityResult, DEFAULT_NDSI_THRESHOLDS,
    calc_si, calc_si1, calc_si2,
    calc_ndsi_salinity, calc_bi, calc_ndvi_mask,
    classify_salinity, compute_salinity_stats,
    get_salinity_colormap, assess_salinity, assess_salinity_cached,
)
from .lst import (
    THERMAL_LEVELS, LSTResult, DEFAULT_THERMAL_THRESHOLDS,
    read_lst_array, kelvin_to_celsius, classify_thermal,
    compute_lst_stats, get_thermal_colormap,
    compute_lst_ndvi_relation, assess_thermal, assess_thermal_cached,
)
from .spectral import (
    BAND_NAMES, PRESET_INDICES, PRESET_INDEX_NAMES, ALLOWED_NUMPY_FUNCS,
    get_band_arrays, evaluate_band_math,
    get_preset_index, compute_index_stats,
)
from .transition import (
    compute_transition_matrix, net_change,
    find_major_transitions, plot_transition_heatmap,
    plot_net_change_bar, analyze_transition,
)
from .aoi import (
    parse_geojson_bbox, validate_bbox, render_aoi_selector,
)
from .demo_mode import (
    is_demo_mode, set_demo_mode, render_demo_mode_toggle,
)
from .evapotranspiration import (
    ET_LEVELS, ETResult, DEFAULT_ET_THRESHOLDS,
    calc_fvc, calc_emissivity, calc_atmospheric_emissivity,
    calc_net_radiation, calc_soil_heat_flux, calc_sensible_heat,
    calc_latent_heat, calc_et_daily,
    classify_et, compute_et_stats, get_et_colormap,
    assess_et, assess_et_cached,
)
from .supervised import (
    CLASSIFIERS, FEATURE_BANDS, INDEX_FEATURES, SupervisedResult,
    build_feature_stack, sample_from_reference,
    sample_from_geojson, sample_from_csv, coords_to_indices,
    train_classifier, predict_image, predict_image_proba,
    evaluate_classification, assess_supervised_classification,
)
from .vector import (
    VECTOR_FORMATS, DEFAULT_AREA_CRS,
    raster_to_gdf, gdf_to_geojson, gdf_to_shapefile, gdf_to_kml,
    raster_to_vector, raster_to_vector_from_file,
    compute_class_areas, summarize_vector,
)
from .results_store import (
    KIND_EXT, TEXT_KINDS, BINARY_KINDS,
    save_result, save_result_file, list_results,
    get_result, get_result_path, load_result,
    delete_result, clear_results, package_results, get_store_info,
)
from .ai_insight import (
    generate_ai_insight, explain_metrics,
    summarize_insight, get_insight_history,
    is_ai_available,
)
from .save_ui import (
    render_save_button, render_save_csv_button,
)
from .preprocess import (
    apply_s2_cloud_mask, apply_landsat_cloud_mask,
    mask_clouds, resample_array, normalize_to_uint8,
    cloud_cover_fraction, mask_stats,
)
from .pdf_report import (
    generate_report_pdf, report_to_pdf_download,
)
from .composite import (
    composite_ndvi_monthly, composite_series_by_month, merge_ndvi_max,
)
from .image_processing import (
    pca_transform, pca_rgb_composite,
    spatial_filter, contrast_enhance, ihs_fusion, enhance_report,
)
from .unsupervised import (
    kmeans_classify, kmeans_feature_stack, auto_describe_classes,
)
from .atmospheric import (
    dos_correction, estimate_dark_pixel, dos_quality_report,
    radiometric_calibration, toa_reflectance, relative_normalization,
    preprocess_pipeline,
)
from .bfast import (
    detect_breaks, chow_test, detect_vegetation_breaks,
    summarize_breaks,
)
from .texture import (
    glcm_texture_maps, glcm_texture_maps_fast, glcm_global_stats,
    build_texture_stack, summarize_texture,
    TEXTURE_PROPS, TEXTURE_NAMES_CN,
)
from .spatial import (
    raster_buffer, buffer_zone_stats, smart_buffer_analysis,
    neighborhood_stats, overlay_crosstab, overlay_analysis_text,
)
from .ai_assistant import (
    chat_with_assistant, auto_analyze, detect_anomalies,
    anomaly_insight, build_platform_context,
)
# 注: ai_assistant 也定义了同名 is_ai_available (实现与 ai_insight 完全相同),
# 此处只保留 ai_insight 的版本, 避免 utils.is_ai_available 被静默覆盖。
from .ai_vision import (
    image_fingerprint, vision_describe, quality_diagnose,
)
from .ai_copilot import (
    generate_research_plan, quick_scan, generate_copilot_report, run_copilot,
)
from .ai_report import (
    generate_full_report, sections_from_sources,
)
from .map_utils import (
    draw_area_schematic, render_area_map,
)
from .empty_states import (
    no_image_guidance, no_data_guidance, no_result_guidance,
)
from .upload_utils import (
    save_upload_stable, cleanup_old_uploads, get_shared_geotiff_path,
)
from .cryosphere import (
    SNOW_COVER_CLASSES, GLACIER_CLASSES, CryosphereResult,
    calc_ndsi, calc_ndsi_nir, calc_snow_cover,
    extract_glacier_mask, estimate_snow_line,
    analyze_frozen_ground, compute_snow_cover_stats,
    compute_glacier_stats, assess_cryosphere,
)
from .agri_drought import (
    AGRI_DROUGHT_LEVELS, AgriDroughtResult,
    calc_cwsi_ndvi, calc_smi_swir, calc_smi_combined,
    calc_mpdi, classify_agri_drought,
    estimate_irrigation_demand, compute_agri_stats,
    assess_agri_drought,
)
from .animation import (
    create_timeseries_animation, create_multi_index_animation,
    create_trend_animation,
)
from .ecology import (
    ECO_SECURITY_LEVELS, EcoSecurityResult,
    calc_psi, calc_ssi, calc_rsi, calc_esi,
    classify_eco_security, compute_eco_stats,
    assess_eco_security,
)


# ============================================
# 公开 API — 集中导出
# ============================================
# 本模块是平台的统一入口 (供 `from utils import xxx` 使用),
# 下列名字即对外契约。声明 __all__ 后, ruff 不再把这里的
# re-export 判定为"未使用导入" (F401)。
__all__ = [
    "AGRI_DROUGHT_LEVELS",
    "ALLOWED_NUMPY_FUNCS",
    "ARID6_CLASSES",
    "AgriDroughtResult",
    "BAND_NAMES",
    "BINARY_KINDS",
    "CLASSIFIERS",
    "CryosphereResult",
    "DEFAULT_AREA_CRS",
    "DEFAULT_ET_THRESHOLDS",
    "DEFAULT_NDSI_THRESHOLDS",
    "DEFAULT_OVERLAP",
    "DEFAULT_SEGMENT_PARAMS",
    "DEFAULT_THERMAL_THRESHOLDS",
    "DEFAULT_WINDOW_SIZE",
    "DESERTIFICATION_LEVELS",
    "DROUGHT_CATEGORIES",
    "DesertificationResult",
    "ECO_SECURITY_LEVELS",
    "ESA_CLASSES",
    "ESA_TO_ARID6",
    "ESRI_CLASSES",
    "ESRI_TO_ARID6",
    "ETResult",
    "ET_LEVELS",
    "EcoSecurityResult",
    "FEATURE_BANDS",
    "ForecastResult",
    "GLACIER_CLASSES",
    "INDEX_FEATURES",
    "KIND_EXT",
    "LSTResult",
    "PRESET_INDEX_NAMES",
    "PRESET_INDICES",
    "SALINITY_LEVELS",
    "SENTINEL2_BAND_ORDER",
    "SNOW_COVER_CLASSES",
    "SPI_THRESHOLDS",
    "SalinityResult",
    "StreamlitErrorBoundary",
    "StreamlitProgress",
    "SupervisedResult",
    "TEXTURE_NAMES_CN",
    "TEXTURE_PROPS",
    "TEXT_KINDS",
    "THERMAL_LEVELS",
    "VCI_THRESHOLDS",
    "VECTOR_FORMATS",
    "analyze_desertification_trend",
    "analyze_drought_forecast",
    "analyze_drought_remote",
    "analyze_frozen_ground",
    "analyze_transition",
    "anomaly_insight",
    "apply_landsat_cloud_mask",
    "apply_s2_cloud_mask",
    "assess_agri_drought",
    "assess_cryosphere",
    "assess_desertification",
    "assess_desertification_cached",
    "assess_eco_security",
    "assess_et",
    "assess_et_cached",
    "assess_salinity",
    "assess_salinity_cached",
    "assess_supervised_classification",
    "assess_thermal",
    "assess_thermal_cached",
    "auto_analyze",
    "auto_describe_classes",
    "benchmark_onnx_vs_pytorch",
    "buffer_zone_stats",
    "build_band_order",
    "build_feature_stack",
    "build_platform_context",
    "build_texture_stack",
    "calc_albedo_landsat",
    "calc_albedo_s2",
    "calc_atmospheric_emissivity",
    "calc_aweish",
    "calc_bi",
    "calc_composite_drought_index",
    "calc_cwsi_ndvi",
    "calc_ddi",
    "calc_emissivity",
    "calc_esi",
    "calc_et_daily",
    "calc_evi",
    "calc_fvc",
    "calc_latent_heat",
    "calc_mean_timeseries_trend",
    "calc_mndwi",
    "calc_mpdi",
    "calc_nddi",
    "calc_ndmi",
    "calc_ndsi",
    "calc_ndsi_nir",
    "calc_ndsi_salinity",
    "calc_ndvi",
    "calc_ndvi_anomaly",
    "calc_ndvi_anomaly_pixelwise",
    "calc_ndvi_mask",
    "calc_ndwi_s2",
    "calc_net_radiation",
    "calc_pet_thornthwaite",
    "calc_psi",
    "calc_rsi",
    "calc_sen_mk_trend",
    "calc_sen_mk_trend_pixelwise",
    "calc_sensible_heat",
    "calc_si",
    "calc_si1",
    "calc_si2",
    "calc_smi_combined",
    "calc_smi_swir",
    "calc_snow_cover",
    "calc_soil_heat_flux",
    "calc_spei",
    "calc_spi",
    "calc_spi_pixelwise",
    "calc_ssi",
    "calc_tci",
    "calc_tci_pixelwise",
    "calc_tgsi",
    "calc_tvdi",
    "calc_vci",
    "calc_vci_pixelwise",
    "calc_vhi",
    "calc_vhi_pixelwise",
    "chat_with_assistant",
    "check_dependencies",
    "check_onnx_available",
    "chow_test",
    "classify_agri_drought",
    "classify_desertification",
    "classify_drought",
    "classify_eco_security",
    "classify_et",
    "classify_salinity",
    "classify_spi",
    "classify_thermal",
    "classify_vci",
    "cleanup_old_uploads",
    "clear_results",
    "cloud_cover_fraction",
    "composite_ndvi_monthly",
    "composite_series_by_month",
    "compute_agri_stats",
    "compute_class_areas",
    "compute_desertification_stats",
    "compute_drought_index_stats",
    "compute_drought_stats",
    "compute_eco_stats",
    "compute_et_stats",
    "compute_glacier_stats",
    "compute_index_stats",
    "compute_landcover_stats",
    "compute_lst_ndvi_relation",
    "compute_lst_stats",
    "compute_salinity_stats",
    "compute_snow_cover_stats",
    "compute_transition_matrix",
    "contrast_enhance",
    "coords_to_indices",
    "create_multi_index_animation",
    "create_timeseries_animation",
    "create_trend_animation",
    "delete_result",
    "detect_anomalies",
    "detect_breaks",
    "detect_vegetation_breaks",
    "dos_correction",
    "dos_quality_report",
    "draw_area_schematic",
    "enhance_report",
    "esa_to_arid6",
    "esri_to_arid6",
    "estimate_dark_pixel",
    "estimate_irrigation_demand",
    "estimate_snow_line",
    "evaluate_band_math",
    "evaluate_classification",
    "evaluate_forecast",
    "explain_metrics",
    "export_array_as_image",
    "export_batch",
    "export_change_polygons_geojson",
    "export_classification_geotiff",
    "export_comparison_figure",
    "export_csv",
    "export_figure",
    "export_index_geotiff",
    "export_landcover_geotiff",
    "export_mask_geotiff",
    "export_numpy",
    "export_raster_geotiff",
    "export_stats_csv",
    "export_timeseries_csv",
    "export_timeseries_plot",
    "export_to_onnx",
    "extract_glacier_mask",
    "find_major_transitions",
    "forecast_drought_trend",
    "forecast_holt_winters",
    "forecast_lstm",
    "forecast_sarima",
    "gdf_to_geojson",
    "gdf_to_kml",
    "gdf_to_shapefile",
    "generate_ai_insight",
    "generate_copilot_report",
    "generate_full_report",
    "generate_report_pdf",
    "generate_research_plan",
    "get_band_arrays",
    "get_desertification_colormap",
    "get_et_colormap",
    "get_insight_history",
    "get_landcover_for_study_area",
    "get_memory_usage_mb",
    "get_model_info",
    "get_ort_session",
    "get_preset_index",
    "get_result",
    "get_result_path",
    "get_salinity_colormap",
    "get_shared_geotiff_path",
    "get_store_info",
    "get_thermal_colormap",
    "get_tile_list_for_area",
    "glcm_global_stats",
    "glcm_texture_maps",
    "glcm_texture_maps_fast",
    "ihs_fusion",
    "image_fingerprint",
    "inspect_onnx_model",
    "is_ai_available",
    "is_demo_mode",
    "kelvin_to_celsius",
    "kmeans_classify",
    "kmeans_feature_stack",
    "list_results",
    "load_bands_from_geotiff",
    "load_result",
    "make_download_label",
    "mask_clouds",
    "mask_stats",
    "merge_ndvi_max",
    "neighborhood_stats",
    "net_change",
    "no_data_guidance",
    "no_image_guidance",
    "no_result_guidance",
    "normalize_to_uint8",
    "overlay_analysis_text",
    "overlay_crosstab",
    "package_results",
    "parse_geojson_bbox",
    "pca_rgb_composite",
    "pca_transform",
    "plot_forecast",
    "plot_forecast_comparison",
    "plot_multilevel_change_stacked_bar",
    "plot_net_change_bar",
    "plot_transition_heatmap",
    "plot_trend_scatter",
    "predict_image",
    "predict_image_proba",
    "prepare_ndvi_timeseries",
    "preprocess_pipeline",
    "quality_diagnose",
    "quick_scan",
    "radiometric_calibration",
    "raster_buffer",
    "raster_to_gdf",
    "raster_to_geojson_polygons",
    "raster_to_vector",
    "raster_to_vector_from_file",
    "read_lst_array",
    "relative_normalization",
    "render_aoi_selector",
    "render_area_map",
    "render_change_overlay",
    "render_classification",
    "render_demo_mode_toggle",
    "render_mndwi",
    "render_multilevel_change",
    "render_ndvi",
    "render_save_button",
    "render_save_csv_button",
    "report_to_pdf_download",
    "resample_array",
    "run_copilot",
    "run_onnx_inference",
    "safe_cleanup",
    "safe_execute",
    "sample_from_csv",
    "sample_from_geojson",
    "sample_from_reference",
    "save_result",
    "save_result_file",
    "save_upload_stable",
    "savgol_smooth",
    "sections_from_sources",
    "segment_water_ai",
    "segment_water_ai_batch",
    "segment_water_onnx",
    "set_demo_mode",
    "smart_buffer_analysis",
    "smooth_ndvi_stack",
    "spatial_filter",
    "split_train_test",
    "stl_decompose",
    "streamlit_safe",
    "summarize_breaks",
    "summarize_insight",
    "summarize_texture",
    "summarize_vector",
    "theil_sen_slope",
    "toa_reflectance",
    "train_classifier",
    "validate_bbox",
    "vision_describe",
    "with_retry",
]
